apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crd-manager
rules:
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]  # Adjust based on your needs

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: githubactions-crd-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: crd-manager
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: github-actions  # This should match the group in your access entry

