{{- if and .Values.autoscaling.enabled (not (and .Values.autoscaling.keda .Values.autoscaling.keda.enabled)) }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "order-service.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "order-service.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "order-service.fullname" . }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
{{- if and .Values.autoscaling.external .Values.autoscaling.external.enabled }}
    - type: External
      external:
        metric:
          name: {{ required "Set .Values.autoscaling.external.metricName when using external metrics" .Values.autoscaling.external.metricName | quote }}
{{- with .Values.autoscaling.external.metricSelector }}
          selector:
            matchLabels:
{{- range $k, $v := . }}
              {{ $k }}: {{ $v | quote }}
{{- end }}
{{- end }}
        target:
          type: {{ default "AverageValue" .Values.autoscaling.external.metricTarget.type }}
{{- if or (not .Values.autoscaling.external.metricTarget.type) (eq .Values.autoscaling.external.metricTarget.type "AverageValue") }}
          averageValue: {{ required "Set .Values.autoscaling.external.metricTarget.value when using external metrics" .Values.autoscaling.external.metricTarget.value | quote }}
{{- else }}
          value: {{ required "Set .Values.autoscaling.external.metricTarget.value when using external metrics" .Values.autoscaling.external.metricTarget.value | quote }}
{{- end }}
{{- else }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.targetCPUUtilizationPercentage }}
{{- if .Values.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.targetMemoryUtilizationPercentage }}
{{- end }}
{{- end }}
{{- end }}
