{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $full := include "order-service.fullname" . -}}{{ $full }}-ingress
  {{- $ann := .Values.ingress.annotations }}
  {{- if or $ann .Values.ingress.certificateArn }}
  annotations:
    {{- if $ann }}
    {{ toYaml $ann | nindent 4 }}
    {{- end }}
    {{- if .Values.ingress.certificateArn }}
    alb.ingress.kubernetes.io/certificate-arn: "{{ .Values.ingress.certificateArn }}"
    {{- end }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className | quote }}
  {{- end }}
  rules:
  {{- range $host := .Values.ingress.hosts }}
    - host: {{ $host.host | quote }}
      http:
        paths:
        {{- range $path := $host.paths }}
          - path: {{ $path.path | default "/" | quote }}
            pathType: {{ $path.pathType | default "Prefix" }}
            backend:
              service:
                name: {{ $full }}
                port:
                  number: {{ $.Values.service.port }}
        {{- end }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
  {{- range $tls := .Values.ingress.tls }}
    - hosts:
      {{- range $h := $tls.hosts }}
        - {{ $h | quote }}
      {{- end }}
      secretName: {{ $tls.secretName | quote }}
  {{- end }}
  {{- end }}
{{- end }}