name: Staging CI Rollout

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
  workflow_dispatch: { }

concurrency:
  group: order-service-${{ github.ref }}
  cancel-in-progress: false

env:
  PYTHON_VERSION: "3.11"
  WORKING_DIRECTORY: order-service-main
  HELM_CHART_PATH: Infrastructure/helm
  DOCKER_IMAGE: chinthika/order-service
  AWS_REGION: us-east-1
  EKS_CLUSTER_NAME: order-service-shared-eks

jobs:
  lint-and-test:
    name: Lint, security scan & tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Cache pip packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ env.PYTHON_VERSION }}-${{ hashFiles('dev-requirements.txt') }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dev-requirements.txt

      - name: Run pytest
        run: |
          python -m pytest --maxfail=1 --disable-warnings

      - name: Run bandit security scan
        run: |
          bandit -r src -ll

      - name: Run pylint
        run: |
          pylint src



  build-scan-and-push-image:
    name: Build and Scan image
    runs-on: ubuntu-latest
    needs:
      - lint-and-test
    outputs:
      image_tag: ${{ steps.meta.outputs.image_tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Determine image tag
        id: meta
        run: |
          echo "image_tag=${GITHUB_SHA::8}" >> "$GITHUB_OUTPUT"

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image (local)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Infrastructure/Dockerfile
          load: true
          push: false
          tags: ${{ env.DOCKER_IMAGE }}:${{ steps.meta.outputs.image_tag }}

      - name: Docker Scout CVE Scan (local image)
        uses: docker/scout-action@v1
        with:
          file: Infrastructure/Dockerfile
          command: cves,recommendations,compare
          ignore-unchanged: true
          to-latest: true
          ignore-base: true
          only-fixed: true
          only-severities: critical,high
          image: ${{ env.DOCKER_IMAGE }}:${{ steps.meta.outputs.image_tag }}
          dockerhub-user: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub-password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push docker image
        uses: docker/build-push-action@v6
        with:
          file: Infrastructure/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ env.DOCKER_IMAGE }}:${{ steps.meta.outputs.image_tag }}
            ${{ env.DOCKER_IMAGE }}:latest
  

  deploy-staging:
    name: Deploy to staging
    runs-on: ubuntu-latest
    needs:
      - build-scan-and-push-image
    if: (github.event_name == 'push' && github.ref == 'refs/heads/develop') || (github.event_name == 'workflow_dispatch')
    env:
      IMAGE_TAG: ${{ needs.build-scan-and-push-image.outputs.image_tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: v1.29.2

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.4

      - name: Configure kubeconfig
        run: aws eks update-kubeconfig --region $AWS_REGION --name ${{ env.EKS_CLUSTER_NAME }}

      - name: Create/update image pull secret
        run: |
          kubectl create namespace staging --dry-run=client -o yaml | kubectl apply -f -
          kubectl create secret docker-registry dockerhub-creds \
            --namespace staging \
            --docker-server=https://index.docker.io/v1/ \
            --docker-username=${{ secrets.DOCKERHUB_USERNAME }} \
            --docker-password=${{ secrets.DOCKERHUB_TOKEN }} \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Deploy chart
        run: |
          helm upgrade --install order-service-staging ${{ env.HELM_CHART_PATH }} \
            --namespace staging --atomic --timeout 5m0s \
            --create-namespace \
            -f ${{ env.HELM_CHART_PATH }}/values.staging.yaml \
            --set image.tag=${{ env.IMAGE_TAG }} \
            --set image.repository=${{ env.DOCKER_IMAGE }} \
            --set ingress.certificateArn=${{ secrets.ACM_CERTIFICATE_ARN }} \
            --set-string newrelic-k8s-metrics-adapter.config.accountID=${{ secrets.NEW_RELIC_ACCOUNT_ID }} \
            --set-string newrelic-k8s-metrics-adapter.personalAPIKey=${{ secrets.NEW_RELIC_API_KEY }} \
            --set env[8].name=NEW_RELIC_LICENSE_KEY --set env[8].value=${{ secrets.NEW_RELIC_LICENSE_KEY }}

      - name: Wait for rollout
        run: kubectl rollout status deployment/order-service-staging -n staging --timeout=180s

  run-regression-tests:
    name: Run regression tests
    runs-on: ubuntu-latest
    needs:
      - deploy-staging
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: v1.29.2

      - name: Configure kubeconfig
        run: aws eks update-kubeconfig --region $AWS_REGION --name ${{ env.EKS_CLUSTER_NAME }}

      - name: Simple Health Check
        run: |
          kubectl -n staging delete job order-service-smoke --ignore-not-found
          kubectl -n staging create job order-service-smoke \
            --image=curlimages/curl:8.5.0 -- \
            curl -fsS --retry 5 --retry-delay 5 \
              http://order-service-staging.staging.svc.cluster.local:8000/health
          kubectl -n staging wait --for=condition=complete --timeout=180s job/order-service-smoke
          kubectl -n staging delete job order-service-smoke
      - name: Run Regression Tests
        run: |
          echo 'Tests would run here...'
  

  create-pr-to-main:
    name: Create PR to main
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    needs:
      - deploy-staging
      - run-regression-tests
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Create PR to main
        if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
        uses: peter-evans/create-pull-request@v7
        with:
          token: '${{ secrets.PERSONAL_GITHUB_TOKEN }}'
          commit-message: 'automated: merge to main branch'
          branch: ${{ github.ref_name }}
          base: main
          title: 'Automated PR → main'
          body: |
            This PR was automatically created by GitHub Actions.
            Triggered from branch `${{ github.ref_name }}`.
          labels: |
            automated
            ci
            deploy to production

